" My vimrc file.

" When started as "evim", evim.vim will already have done these settings.
if v:progname =~? "evim"
  finish
endif

if v:lang =~ "utf8$" || v:lang =~ "UTF-8$"
   set fileencodings=utf-8,latin1
endif

set nocompatible	" Use Vim defaults (much better!)

" I use an indent of 4 in my code... but leave normal tabs at 8!
set shiftwidth=4
set softtabstop=4
set autoindent

set expandtab

" set lines=50
set columns=130
set number

" allow backspacing over everything in insert mode
set backspace=indent,eol,start
"set ai			" always set autoindenting on
set viminfo='20,\"50	" read/write a .viminfo file, don't store more
			" than 50 lines of registers
set history=50		" keep 50 lines of command line history
set ruler		" show the cursor position all the time
set incsearch           " Do search as one entries the search target
set laststatus=2

set noerrorbells
set vb t_vb=

" All my user commands start with F12
"let mapleader = "\<F12>"
"let mapleader = "-"

"edit my vimrc file
nnoremap <F12>ev :vsplit $MYVIMRC<cr>

nnoremap <F12>sv :source $MYVIMRC<cr>

"Stop the default menus in gvim (we want our own)
let did_install_default_menus = 4

" Only do this part when compiled with support for autocommands
if has("autocmd")
  " In text files, always limit the width of text to 78 characters
  autocmd BufRead *.txt set tw=78
  " When editing a file, always jump to the last cursor position
  autocmd BufReadPost *
  \ if line("'\"") > 0 && line ("'\"") <= line("$") |
  \   exe "normal! g'\"" |
  \ endif
endif

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

filetype plugin indent on

autocmd FileType html set shiftwidth=2
autocmd FileType html set softtabstop=2

if &term=="xterm"
     set t_Co=8        " Set number of colours to 8 (same as linux console)
     set t_Sb=[4%dm
     set t_Sf=[3%dm
endif
